# open id clients
[[clients]]
id = "auth"
grant-types = [ "authorization_code", "refresh_token" ]
response-types = [ "code", "id_token" ]
scope = [ "openid", "offline" ]
callback = "https://auth.coldwire.org/api/callback"
token-endpoint-auth-method = "none"

[[clients]]
id = "bloc"
grant-types = [ "authorization_code", "refresh_token" ]
response-types = [ "code", "id_token" ]
scope = [ "openid", "offline" ]
callback = "https://bloc.coldwire.org/api/user/auth/oauth2/callback"
token-endpoint-auth-method = "none"
