[server]
address = "0.0.0.0"
port = "3003"
auth-url = "http://127.0.0.1:3003"
auth-secret = "acab1312"

[database]
driver = "postgres"

  [database.postgres]
  address = "127.0.0.1"
  port = "5432"
  user = "postgres"
  password = "acab"
  name = "auth"

[hydra]
proxy = "true"
admin = "http://127.0.0.1:4445"
public = "http://127.0.0.1:4444/"