[server]
address = "0.0.0.0"
port = "3003"
auth-url = "http://127.0.0.1:3003"
auth-secret = "acab1312"

[database]
driver = "sqlite"

  [database.postgres]
  address = "127.0.0.1"
  port = "5432"
  user = "postgres"
  password = "4llc0ps4re64st4rds"
  name = "auth"

  [database.sqlite]
  path = "./db.sqlite"

[hydra]
proxy = "true"
admin = "http://127.0.0.1:4445"
public = "http://127.0.0.1:4444/"

  [[hydra.clients]]
  ClientId = "bloc"
  ClientSecret = "acab1312"
  GrantTypes = ["authorization_code", "refresh_token"]
  ResponseTypes = ["code", "id_token"]
  Scope = "openid,offline"
  RedirectUris = ["http://127.0.0.1:3002/api/user/auth/oauth2/callback"]
  TokenEndpointAuthMethod = "client_secret_post"