serve:
  cookies:
    same_site_mode: Lax

urls:
  self:
    issuer: http://127.0.0.1:3003/
    public: http://127.0.0.1:4444/
  consent: http://127.0.0.1:3003/api/auth/consent
  login: http://127.0.0.1:3003/#/sign-in
  logout: http://127.0.0.1:3003/api/auth/logout
  post_logout_redirect: http://127.0.0.1:3003/#/sign-in