version: '3.7'
services:
  hydra:
    image: oryd/hydra:v1.11.8
    ports:
      - "4444:4444" # Public port
      - "4445:4445" # Admin port
    command: serve -c /etc/config/hydra/hydra.yml all --dangerous-force-http
    volumes:
      - type: bind
        source: ./hydra-dev-config.yml
        target: /etc/config/hydra/hydra.yml
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=ThisIsJustASuperToken!
    restart: unless-stopped
    depends_on:
      - hydra-migrate
    networks:
      - intranet
  hydra-migrate:
    image: oryd/hydra:v1.11.8
    environment:
      - DSN=postgres://hydra:secret@postgresd:5432/hydra?sslmode=disable&max_conns=20&max_idle_conns=4
      - SECRETS_SYSTEM=ThisIsJustASuperToken!
    command: migrate -c /etc/config/hydra/hydra.yml sql -e --yes
    volumes:
      - type: bind
        source: ./hydra-dev-config.yml
        target: /etc/config/hydra/hydra.yml
    restart: on-failure
    networks:
      - intranet
  postgresd:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=hydra
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=hydra
    networks:
      - intranet
networks:
  intranet: