package auth

import (
	"auth/models"
	"auth/utils"
	"time"

	"auth/utils/errors"
	"auth/utils/tokens"

	"codeberg.org/coldwire/cwhydra"
	"github.com/alexedwards/argon2id"
	"github.com/gofiber/fiber/v2"
)

func Register(c *fiber.Ctx) error {
	username := c.FormValue("username")
	password := c.FormValue("password")

	// Get generated keys
	pvkey := c.FormValue("pvkey")
	pbkey := c.FormValue("pbkey")

	challenge := c.Query("login_challenge") // get challenge generated by hydra

	user := models.User{
		Name: username,
	}

	// Verify that the username is not empty or too short
	if username == "" {
		return errors.Handle(c, errors.ErrBody)
	}

	// Verify if the user already exist
	exist := user.Exist()
	if exist {
		return errors.Handle(c, errors.ErrAuthExist)
	}

	// Hash password with argon2id
	hash, err := argon2id.CreateHash(password, argon2id.DefaultParams)
	if err != nil {
		return errors.Handle(c, errors.ErrUnknown, err)
	}

	// If this is the first user to register, makes them admin
	isFirstUser := user.IsFirstOne()

	if isFirstUser {
		user.Group = "admin"
	} else {
		user.Group = "user"
	}

	// Set user data
	user.Password = hash
	user.PrivateKey = pvkey
	user.PublicKey = pbkey

	err = user.Create()
	if err != nil {
		return errors.Handle(c, errors.ErrDatabaseCreate, err)
	}

	usrData := tokens.Token{
		Username:   user.Name,
		Group:      user.Group,
		PrivateKey: user.PrivateKey,
		PublicKey:  user.PublicKey,
	}

	cookie := tokens.Generate(usrData, 24*time.Hour)

	utils.SetCookie(c, "token", cookie, time.Now())

	if challenge == "" {
		return errors.Handle(c, errors.Success, usrData)
	} else {
		redirect, err := cwhydra.LoginManager(*cwhydra.AdminApi).Accept(challenge, cwhydra.AcceptLoginRequest{
			Subject: username,
			Context: map[string]interface{}{
				"username":    username,
				"role":        user.Group,
				"private_key": user.PrivateKey,
				"public_key":  user.PublicKey,
			},
			Remember: true,
		})
		if err != nil {
			return errors.Handle(c, errors.ErrUnknown, err)
		}

		return c.Redirect(redirect)
	}
}
